
package fr.cnamts.webservice;

import javax.xml.ws.WebFault;
import siram.TypeErreur;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Erreur", targetNamespace = "urn:siram")
public class Erreur
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TypeErreur faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Erreur(String message, TypeErreur faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Erreur(String message, TypeErreur faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: siram.TypeErreur
     */
    public TypeErreur getFaultInfo() {
        return faultInfo;
    }

}
