
package fr.cnamts.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import fr.cnamts.insirecsans.TraitsDIdentite;
import fr.cnamts.insirecvit.Beneficiaire;
import fr.cnamts.insiresultat.Resultat;
import org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.TypeSecurity;
import org.w3._2005._08.addressing.AttributedURIType;
import siram.bam.ctxbam.ContexteBAM;
import siram.lps.ctxlps.ContexteLPS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICIRService", targetNamespace = "http://www.cnamts.fr/webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    fr.cnamts.insirecsans.ObjectFactory.class,
    fr.cnamts.insirecvit.ObjectFactory.class,
    fr.cnamts.insiresultat.ObjectFactory.class,
    oasis.names.tc.saml._2_0.assertion.ObjectFactory.class,
    org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    org.w3._2001._04.xmlenc_.ObjectFactory.class,
    org.w3._2005._08.addressing.ObjectFactory.class,
    siram.ObjectFactory.class,
    siram.bam.ctxbam.ObjectFactory.class,
    siram.lps.ctxlps.ObjectFactory.class
})
public interface ICIRService {


    /**
     * 
     * @param no1Security
     * @param no1ContexteBAM
     * @param no1ContexteLPS
     * @param no1MessageID
     * @param rechercherInsAvecCarteVitale
     * @return
     *     returns fr.cnamts.insiresultat.Resultat
     * @throws Erreur
     */
    @WebMethod(action = "urn:ServiceIdentiteCertifiee:1.0.0:rechercherInsAvecCarteVitale")
    @WebResult(name = "RESULTAT", targetNamespace = "http://www.cnamts.fr/INSiResultat", partName = "rechercherInsAvecCarteVitaleResponse")
    public Resultat rechercherInsAvecCarteVitale(
        @WebParam(name = "RECVITALE", targetNamespace = "http://www.cnamts.fr/INSiRecVit", partName = "rechercherInsAvecCarteVitale")
        Beneficiaire rechercherInsAvecCarteVitale,
        @WebParam(name = "Security", targetNamespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", header = true, partName = "NO1_Security")
        TypeSecurity no1Security,
        @WebParam(name = "ContexteLPS", targetNamespace = "urn:siram:lps:ctxlps", header = true, partName = "NO1_ContexteLPS")
        ContexteLPS no1ContexteLPS,
        @WebParam(name = "MessageID", targetNamespace = "http://www.w3.org/2005/08/addressing", header = true, partName = "NO1_MessageID")
        AttributedURIType no1MessageID,
        @WebParam(name = "ContexteBAM", targetNamespace = "urn:siram:bam:ctxbam", header = true, partName = "NO1_ContexteBAM")
        ContexteBAM no1ContexteBAM)
        throws Erreur
    ;

    /**
     * 
     * @param no1Security
     * @param rechercherInsAvecTraitsIdentite
     * @param no1ContexteBAM
     * @param no1ContexteLPS
     * @param no1MessageID
     * @return
     *     returns fr.cnamts.insiresultat.Resultat
     * @throws Erreur
     */
    @WebMethod(action = "urn:ServiceIdentiteCertifiee:1.0.0:rechercherInsAvecTraitsIdentite")
    @WebResult(name = "RESULTAT", targetNamespace = "http://www.cnamts.fr/INSiResultat", partName = "rechercherInsAvecTraitsIdentiteResponse")
    public Resultat rechercherInsAvecTraitsIdentite(
        @WebParam(name = "RECSANSVITALE", targetNamespace = "http://www.cnamts.fr/INSiRecSans", partName = "rechercherInsAvecTraitsIdentite")
        TraitsDIdentite rechercherInsAvecTraitsIdentite,
        @WebParam(name = "Security", targetNamespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", header = true, partName = "NO1_Security")
        TypeSecurity no1Security,
        @WebParam(name = "ContexteLPS", targetNamespace = "urn:siram:lps:ctxlps", header = true, partName = "NO1_ContexteLPS")
        ContexteLPS no1ContexteLPS,
        @WebParam(name = "MessageID", targetNamespace = "http://www.w3.org/2005/08/addressing", header = true, partName = "NO1_MessageID")
        AttributedURIType no1MessageID,
        @WebParam(name = "ContexteBAM", targetNamespace = "urn:siram:bam:ctxbam", header = true, partName = "NO1_ContexteBAM")
        ContexteBAM no1ContexteBAM)
        throws Erreur
    ;

}
